apiVersion: apps/v1
kind: Deployment
metadata:
  name: maineCoon
  labels:
    app: maineCoon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maineCoon
  template:
    metadata:
      labels:
        app: maineCoon
    spec:
      containers:
        - name: maineCoon-ui
          image: gabyorel/mainecoon-app:ui-develop 
          ports:
            - containerPort: 3334
        - name: mainCoon-api
          image: gabyorel/mainecoon-app:api-develop
          ports:
            - containerPort: 3333
      imagePullSecrets:
        - name: regcred  # Si l'image est privée, voir plus bas
---
apiVersion: v1
kind: Service
metadata:
  name: maineCoon-service
spec:
  selector:
    app: maineCoon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3334
  type: LoadBalancer  # Expose l'application via un LoadBalancer AWS
