upstream Backend {
    # api is the internal DNS name used by the backend Service inside Kubernetes
    server api;
}

server {
    listen 80;

    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /user/ {
        proxy_pass http://Backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
