name: docker-image

on:
  push:
    branches:
      - develop
      - main
    paths:
      - ./api/**
      - ./ui/**

  pull_request:
    branches:
      - develop
      - main
    paths:
      - ./api/**
      - ./ui/**

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'
            ui:
              - 'ui/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for api
        if: steps.changes.outputs.api == 'true'
        id: meta-api
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/mainecoon-api
          tags: |
            ${{ github.ref_name }}
  
      - name: Build and push api image
        if: steps.changes.outputs.api == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      - name: Extract metadata for ui
        if: steps.changes.outputs.ui == 'true'
        id: meta-ui
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/mainecoon-ui
          tags: |
            ${{ github.ref_name }}

      - name: Build and push ui image
        if: steps.changes.outputs.ui == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./ui
          push: true
          tags: ${{ steps.meta-ui.outputs.tags }}
          labels: ${{ steps.meta-ui.outputs.labels }}
